name: .NET Core Deploy

on:
  push:
    branches: [ release ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.*'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --output thichngamxe.vn

    - name: Zip Publish Output
      run: zip -r thichngamxe.vn.zip thichngamxe.vn/

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/thichngamxe.vn
          ls -lrt
          rm -rf *
          scp $GITHUB_WORKSPACE/publish.zip ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/
          unzip thichngamxe.vn.zip -d .
  